### PR TITLE
bring back erlang build process messages

### PR DESCRIPTION
**Pull request by JakaBac**
After upgrading to 2018.1 the Erlang build errors and warnings are not displayed anymore.
Even if the compilation fails it looks like that everything succeeded, but no beam files get generated

The reason for this is:

`java.lang.NoClassDefFoundError: com/intellij/openapi/compiler/CompilerMessageCategory`

This replaces `CompilerMessageCategory` with `BuildMessage.Kind`

### CODE REVIEW

**Comment by ignatov** [comment]
Also, I've just uploaded a new plugin update https://plugins.jetbrains.com/plugin/7083-erlang/update/44598
